# Generated by Django 5.2.16 on 2026-07-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_carouselslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fabric',
            field=models.CharField(default='100% Organic Combed Cotton (Heavyweight)', max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(default='240 GSM (Oversized) / 400 GSM (Hoodies)', max_length=100),
        ),
    ]
