# Generated by Django 5.2.16 on 2026-07-15 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_fabric_product_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='gender',
        ),
    ]
