# Generated by Django 5.2.16 on 2026-07-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_address_email_address_full_name_address_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, help_text='Upload an icon or image for this feature section', null=True, upload_to='features/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordering position')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
