# Generated by Django 5.2.16 on 2026-07-19 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_razorpay_order_id_order_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cashfree_order_id',
        ),
    ]
