# Generated by Django 5.2.16 on 2026-07-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_order_shipping_partner_tracking_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='⚡ Chennai Delivery in 1-3 Days • Buy 2 Get 1 Free • Express Shipping across Tamil Nadu ⚡', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
