# Generated by Django 5.2.16 on 2026-07-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_wishlist_unique_together_wishlist_session_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_new_arrival',
            field=models.BooleanField(default=True, help_text='Show in New Arrivals section on homepage'),
        ),
    ]
